frr defaults datacenter
!
!
interface Ethernet1-1
  ip address 10.0.0.12/31
!
interface Ethernet1-2
  ip address 10.0.0.14/31
!
interface Ethernet1-3
  ip address 172.16.0.9/30
!
interface Ethernet1-4
  ip address 172.16.0.13/30
!
!
router bgp 65014
  maximum-paths 64
  neighbor 10.0.0.13 remote-as 65005
  neighbor 10.0.0.15 remote-as 65006
  network 172.16.0.12/30
  network 172.16.0.8/30
