frr defaults datacenter
!
!
interface Ethernet1-1
  ip address 10.0.0.24/31
!
interface Ethernet1-2
  ip address 10.0.0.26/31
!
interface Ethernet1-3
  ip address 172.16.0.17/30
!
interface Ethernet1-4
  ip address 172.16.0.21/30
!
!
router bgp 65015
  maximum-paths 64
  neighbor 10.0.0.25 remote-as 65007
  neighbor 10.0.0.27 remote-as 65008
  network 172.16.0.16/30
  network 172.16.0.20/30
